@startuml
skinparam nodesep 60
skinparam ranksep 20
state Iteration2.Task1 #lightGreen
state Iteration2.Task2 #lightGreen
state Iteration2.Task3 #lightGreen
state Iteration2.Task4 #lightGreen
state Iteration2.Task5 #lightGreen
state Iteration2.Task6 #lightGreen
state Iteration4.Task7 #lightGreen
state Iteration4.Task8 #yellow
state Iteration3.Task9 #lightGreen
state Iteration5.Task10 #lightBlue
state Iteration5.Task11 #pink
state Iteration4.Task14 #yellow
state Iteration3.Task15 #lightGreen
state Iteration4.Task16 #pink
state Iteration4.Task17 #lightBlue
state Iteration4.Task18 #pink
Iteration2.Task1 : P0
Iteration2.Task1 : S3
Iteration2.Task2 : P3
Iteration2.Task2 : S2
Iteration2.Task3 : P1
Iteration2.Task3 : S3
Iteration2.Task4 : P3
Iteration2.Task4 : S2
Iteration2.Task5 : P2
Iteration2.Task5 : S1
Iteration2.Task6 : P3
Iteration2.Task6 : S1
Iteration4.Task7 : P4
Iteration4.Task7 : S5
Iteration4.Task8 : P5
Iteration4.Task8 : S2
Iteration3.Task9 : P5
Iteration3.Task9 : S2
Iteration5.Task10 : P2
Iteration5.Task10 : S4
Iteration5.Task11 : P1
Iteration5.Task11 : S4
Iteration4.Task14 : P5
Iteration4.Task14 : S4
Iteration3.Task15 : P5
Iteration3.Task15 : S5
Iteration4.Task16 : P5
Iteration4.Task16 : S4
Iteration4.Task17 : P5
Iteration4.Task17 : S3
Iteration4.Task18 : P5
Iteration4.Task18 : S5
[*] --> Task1
note on link 
red: blocked
blue: avalible
yellow: under development
green: done 
end note
Task1 --> Task2
Task1 --> Task3
Task3 --> Task4
Task3 --> Task5
Task5 --> Task6
Task5 --> Task7
Task5 --> Task8
Task5 --> Task15
Task6 --> Task9
Task15 --> Task10
Task10 --> Task11
Task15 --> Task14
Task8 --> Task16
Task14 --> Task16
Task7 --> Task17
Task16 --> Task18
@enduml